# Generated by Django 6.0 on 2025-12-09 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_shelter_userprofile_shelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('age_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age_months', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('health_status', models.TextField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Availabale'), ('ADOPTED', 'Adopted'), ('PENDING', 'Pending')], default='AVAILABLE', max_length=20)),
                ('adoption_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pet_image', models.FileField(blank=True, null=True, upload_to='pets/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='PetLogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('age_years', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField()),
                ('pet_image', models.CharField(blank=True, max_length=500)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pets.pet')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
