# Generated by Django 6.0 on 2025-12-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petloghistory',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='pets.pet'),
        ),
    ]
