# Generated by Django 6.0 on 2025-12-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_petloghistory_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petloghistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='petloghistory',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='history', serialize=False, to='pets.pet'),
        ),
    ]
