# Generated by Django 6.0 on 2025-12-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_petloghistory_id_alter_petloghistory_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='petloghistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petloghistory',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='pets.pet'),
        ),
    ]
