# Generated by Django 5.2.7 on 2026-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_petloghistory_id_alter_petloghistory_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCareTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='tips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ADOPTED', 'Adopted'), ('PENDING', 'Pending')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SHELTER', 'Shelter Staff'), ('ADOPTER', 'Adopter')], default='ADOPTER', max_length=20),
        ),
    ]
