# Generated by Django 5.2.7 on 2026-01-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_petcaretip_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcaretip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tips/'),
        ),
    ]
