# Generated by Django 5.2.7 on 2026-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_add_logo_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='pet_image',
            field=models.FileField(blank=True, null=True, upload_to='adoption_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.FileField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='petcaretip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='care_tips/'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_logos/'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='logo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='shelter_logos/thumbs/'),
        ),
    ]
