# Generated by Django 5.2.7 on 2026-01-17 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcaretip',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
